/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class embedded_cse_cau_ac_kr_test3_NDK */

#ifndef _Included_embedded_cse_cau_ac_kr_test3_NDK
#define _Included_embedded_cse_cau_ac_kr_test3_NDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     embedded_cse_cau_ac_kr_test3_NDK
 * Method:    scanning
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_embedded_cse_cau_ac_kr_test3_NDK_scanning
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
